### ISSUE TITLE
how can i change timeline to the left of screen but not the top 

### ISSUE THREAD

**Issue by LanHuangJG** [oleksandrbalan/programguide#7]
as the title said,think you very much

**Comment by oleksandrbalan** [comment]
Do you want to swap positions of the timeline and channels? 

I am afraid it is not possible, because `ProgramGuide` is build as an EPG layout, which I think has timeline always on the top.

However good news are, that `ProgramGuide` uses [MinaBox](https://github.com/oleksandrbalan/minabox) layout, which can be used to create your own lazy layout with timeline to the left. You can check `ProgramGuide` source code for an inspiration.
